services:
    app:
        image: node:18
        container_name: retourne-au-francais
        working_dir: /usr/src/app
        volumes:
            - .:/usr/src/app
        ports:
            - "3000:3000"
        command: >
            sh -c "
            npm install &&
            tail -f /dev/null
            "
